apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gochat
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: go-chat-msa
    app.kubernetes.io/instance: {{ .Release.Namespace }}
spec:
  gatewayClassName: gochat-traefik
  listeners:
  - name: http
    port: 8000
    protocol: HTTP
    hostname: {{ .Values.global.host | quote }}
    allowedRoutes:
      namespaces:
        from: Same
