apiVersion: v1
kind: Secret
metadata:
  name: gochat-secret
  labels:
    app.kubernetes.io/name: gochat-secret
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: go-chat-msa
    app.kubernetes.io/instance: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  APP_JWT_SECRET: dev_secret_key_1234
  APP_INTERNAL_SECRET: dev_internal_secret_1234
  APP_DB_POSTGRES_URL: postgres://postgres:dev_postgres_password@postgres:5432/go_chat?sslmode=disable
  APP_DB_MONGO_URI: mongodb://mongo:27017
  POSTGRES_PASSWORD: dev_postgres_password
  GRAFANA_ADMIN_PASSWORD: dev_grafana_password
