apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - config-files.yaml
  - secret.yaml
  - postgres.yaml
  - mongo.yaml
  - redis.yaml
  - observability.yaml
  - migrations.yaml
  - user-service.yaml
  - chat-service.yaml
  - api-gateway.yaml
  - websocket-service.yaml
  - ws-gateway.yaml
  - frontend.yaml
  - ingress.yaml
