apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-chat-qa

resources:
  - ../../../base/apps
  - websocket-service-hpa.yaml

configMapGenerator:
  - name: gochat-app-config
    behavior: merge
    files:
      - override.yaml=config/app/override.yaml

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: Deployment
      name: api-gateway
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext
        value:
          sysctls:
            - name: net.core.somaxconn
              value: "65535"
  - target:
      kind: Deployment
      name: user-service
    patch: |-
      - op: add
        path: /spec/strategy
        value:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
      - op: add
        path: /spec/template/spec/securityContext
        value:
          sysctls:
            - name: net.core.somaxconn
              value: "65535"
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: "4"
  - target:
      kind: Deployment
      name: chat-service
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext
        value:
          sysctls:
            - name: net.core.somaxconn
              value: "65535"
  - target:
      kind: Deployment
      name: websocket-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/securityContext
        value:
          sysctls:
            - name: net.core.somaxconn
              value: "65535"
  - target:
      kind: Deployment
      name: ws-gateway
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext
        value:
          sysctls:
            - name: net.core.somaxconn
              value: "65535"
  - target:
      kind: Ingress
    patch: |-
      - op: add
        path: /spec/rules/0/host
        value: qa.gochat.localhost

images:
  - name: go-chat-msa/api-gateway
    newTag: qa
  - name: go-chat-msa/ws-gateway
    newTag: qa
  - name: go-chat-msa/websocket-service
    newTag: qa
  - name: go-chat-msa/user-service
    newTag: qa
  - name: go-chat-msa/chat-service
    newTag: qa
  - name: go-chat-msa/frontend
    newTag: qa

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/part-of: go-chat-msa
      app.kubernetes.io/instance: go-chat-qa
