apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: go-chat-qa
resources:
  - ../../../base/apps
  - websocket-service-hpa.yaml
configMapGenerator:
  - name: gochat-app-config
    behavior: merge
    files:
      - override.yaml=config/app/override.yaml
patches:
  - target:
      kind: Deployment
      name: api-gateway
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext/sysctls
        value:
        - name: net.core.somaxconn
          value: '65535'
  - target:
      kind: Deployment
      name: user-service
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext/sysctls
        value:
        - name: net.core.somaxconn
          value: '65535'
  - target:
      kind: Deployment
      name: chat-service
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext/sysctls
        value:
        - name: net.core.somaxconn
          value: '65535'
  - target:
      kind: Deployment
      name: websocket-service
    patch: |-
      - op: remove
        path: /spec/replicas
      - op: add
        path: /spec/template/spec/securityContext/sysctls
        value:
        - name: net.core.somaxconn
          value: '65535'
  - target:
      kind: HTTPRoute
    patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - qa.gochat.localhost
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/part-of: go-chat-msa
      app.kubernetes.io/instance: go-chat-qa
