apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k6-c10k-job.yaml
  - ../../../../test/load
configMapGenerator:
  - name: k6-load-env
    options:
      disableNameSuffixHash: true
    literals:
      - API_HOST=api-gateway
      - API_PORT=8080
      - WS_HOST=websocket-service
      - WS_PORT=8081
      - K6_WORKER_VUS=
      - K6_RAMP_DURATION=
      - K6_PLATEAU_DURATION=
      - K6_RAMP_DOWN_DURATION=
