apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        customQuery: true
        query: '{} | json | trace_id="${__trace.traceId}"'
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus
