apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: go-chat-msa
    app.kubernetes.io/instance: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 50051
    targetPort: grpc
  selector:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: go-chat-msa
    app.kubernetes.io/instance: {{ .Release.Namespace }}
