apiVersion: v1
kind: Service
metadata:
  name: swagger-ui
  labels:
    app.kubernetes.io/name: swagger-ui
    app.kubernetes.io/component: docs
    app.kubernetes.io/part-of: go-chat-msa
    app.kubernetes.io/instance: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app.kubernetes.io/name: swagger-ui
    app.kubernetes.io/component: docs
    app.kubernetes.io/part-of: go-chat-msa
    app.kubernetes.io/instance: {{ .Release.Namespace }}
