global:
  appConfig:
    override:
      ENV: dev
      TELEMETRY:
        OTEL_ENDPOINT: alloy:4318
        PYROSCOPE_ENDPOINT: http://pyroscope:4040
      WEBSOCKET:
        ALLOWED_ORIGINS:
        - http://dev.gochat.localhost:30080
  host: dev.gochat.localhost
  externalPort: 30080
  sysctls:
  - name: net.core.somaxconn
    value: '65535'
api-gateway:
  replicas: 1
user-service:
  replicas: 1
chat-service:
  replicas: 1
websocket-service:
  replicas: 2
  autoscaling:
    enabled: false
