global:
  host: dev.gochat.localhost
  externalPort: 30080
prometheus-adapter:
  enabled: false
grafana:
  env:
    GF_SERVER_ROOT_URL: http://dev.gochat.localhost:30080/grafana/
  route:
    main:
      hostnames:
      - dev.gochat.localhost
