// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	Used      bool
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Room struct {
	ID        pgtype.UUID
	Name      string
	ManagerID pgtype.UUID
	Capacity  int32
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type RoomMember struct {
	UserID   pgtype.UUID
	RoomID   pgtype.UUID
	JoinedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}
