// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateRoomMember(ctx context.Context, arg CreateRoomMemberParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteRoom(ctx context.Context, arg DeleteRoomParams) (pgtype.UUID, error)
	DeleteRoomMember(ctx context.Context, arg DeleteRoomMemberParams) error
	DeleteUser(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	ExistsRoomMember(ctx context.Context, arg ExistsRoomMemberParams) (bool, error)
	GetMemberJoinedAt(ctx context.Context, arg GetMemberJoinedAtParams) (pgtype.Timestamptz, error)
	GetOldestRoomMember(ctx context.Context, roomID pgtype.UUID) (pgtype.UUID, error)
	GetRoomForUpdate(ctx context.Context, id pgtype.UUID) (GetRoomForUpdateRow, error)
	GetRoomMemberCount(ctx context.Context, roomID pgtype.UUID) (int64, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsersByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetUsersByIDsRow, error)
	ListJoinedRoomIDsForUpdate(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error)
	ListJoinedRooms(ctx context.Context, userID pgtype.UUID) ([]ListJoinedRoomsRow, error)
	ListRoomMembers(ctx context.Context, roomID pgtype.UUID) ([]ListRoomMembersRow, error)
	SearchRooms(ctx context.Context, arg SearchRoomsParams) ([]SearchRoomsRow, error)
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (pgtype.UUID, error)
	UpdateRoomManager(ctx context.Context, arg UpdateRoomManagerParams) error
}

var _ Querier = (*Queries)(nil)
