// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateRoom(ctx context.Context, arg CreateRoomParams) (CreateRoomRow, error)
	CreateRoomMember(ctx context.Context, arg CreateRoomMemberParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error
	DeleteRefreshTokensByUserID(ctx context.Context, userID pgtype.UUID) error
	DeleteRoomMember(ctx context.Context, arg DeleteRoomMemberParams) error
	ExistsRoomMember(ctx context.Context, arg ExistsRoomMemberParams) (bool, error)
	GetMemberJoinedAt(ctx context.Context, arg GetMemberJoinedAtParams) (pgtype.Timestamptz, error)
	GetOldestRoomMember(ctx context.Context, roomID pgtype.UUID) (pgtype.UUID, error)
	GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRoomForUpdate(ctx context.Context, id pgtype.UUID) (GetRoomForUpdateRow, error)
	GetRoomMemberCount(ctx context.Context, roomID pgtype.UUID) (int64, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListJoinedRooms(ctx context.Context, userID pgtype.UUID) ([]ListJoinedRoomsRow, error)
	ListRoomMembers(ctx context.Context, roomID pgtype.UUID) ([]ListRoomMembersRow, error)
	MarkRefreshTokenUsed(ctx context.Context, id pgtype.UUID) error
	PurgeDeletedRooms(ctx context.Context, deletedAt pgtype.Timestamptz) (int64, error)
	SearchRooms(ctx context.Context, arg SearchRoomsParams) ([]SearchRoomsRow, error)
	SoftDeleteRoom(ctx context.Context, arg SoftDeleteRoomParams) (pgtype.UUID, error)
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (pgtype.UUID, error)
	UpdateRoomManager(ctx context.Context, arg UpdateRoomManagerParams) error
}

var _ Querier = (*Queries)(nil)
