// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (
  id, name, manager_id, capacity, created_at
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, name, manager_id, capacity, created_at
`

type CreateRoomParams struct {
	ID        pgtype.UUID
	Name      string
	ManagerID pgtype.UUID
	Capacity  int32
	CreatedAt pgtype.Timestamptz
}

type CreateRoomRow struct {
	ID        pgtype.UUID
	Name      string
	ManagerID pgtype.UUID
	Capacity  int32
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (CreateRoomRow, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.ID,
		arg.Name,
		arg.ManagerID,
		arg.Capacity,
		arg.CreatedAt,
	)
	var i CreateRoomRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ManagerID,
		&i.Capacity,
		&i.CreatedAt,
	)
	return i, err
}

const createRoomMember = `-- name: CreateRoomMember :exec
INSERT INTO room_members (
  user_id, room_id, joined_at
) VALUES (
  $1, $2, $3
) ON CONFLICT (user_id, room_id) DO NOTHING
`

type CreateRoomMemberParams struct {
	UserID   pgtype.UUID
	RoomID   pgtype.UUID
	JoinedAt pgtype.Timestamptz
}

func (q *Queries) CreateRoomMember(ctx context.Context, arg CreateRoomMemberParams) error {
	_, err := q.db.Exec(ctx, createRoomMember, arg.UserID, arg.RoomID, arg.JoinedAt)
	return err
}

const deleteRoomMember = `-- name: DeleteRoomMember :exec
DELETE FROM room_members
WHERE room_id = $1 AND user_id = $2
`

type DeleteRoomMemberParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteRoomMember(ctx context.Context, arg DeleteRoomMemberParams) error {
	_, err := q.db.Exec(ctx, deleteRoomMember, arg.RoomID, arg.UserID)
	return err
}

const existsRoomMember = `-- name: ExistsRoomMember :one
SELECT EXISTS (
  SELECT 1 FROM room_members rm
  JOIN rooms r ON r.id = rm.room_id
  WHERE rm.room_id = $1 AND rm.user_id = $2 AND r.deleted_at IS NULL
) AS exists
`

type ExistsRoomMemberParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) ExistsRoomMember(ctx context.Context, arg ExistsRoomMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsRoomMember, arg.RoomID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getMemberJoinedAt = `-- name: GetMemberJoinedAt :one
SELECT rm.joined_at
FROM room_members rm
JOIN rooms r ON r.id = rm.room_id
WHERE rm.room_id = $1 AND rm.user_id = $2 AND r.deleted_at IS NULL
LIMIT 1
`

type GetMemberJoinedAtParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetMemberJoinedAt(ctx context.Context, arg GetMemberJoinedAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getMemberJoinedAt, arg.RoomID, arg.UserID)
	var joined_at pgtype.Timestamptz
	err := row.Scan(&joined_at)
	return joined_at, err
}

const getOldestRoomMember = `-- name: GetOldestRoomMember :one
SELECT user_id FROM room_members
WHERE room_id = $1
ORDER BY joined_at ASC
LIMIT 1
`

func (q *Queries) GetOldestRoomMember(ctx context.Context, roomID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getOldestRoomMember, roomID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getRoomForUpdate = `-- name: GetRoomForUpdate :one
SELECT id, name, manager_id, capacity FROM rooms
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

type GetRoomForUpdateRow struct {
	ID        pgtype.UUID
	Name      string
	ManagerID pgtype.UUID
	Capacity  int32
}

func (q *Queries) GetRoomForUpdate(ctx context.Context, id pgtype.UUID) (GetRoomForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRoomForUpdate, id)
	var i GetRoomForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ManagerID,
		&i.Capacity,
	)
	return i, err
}

const getRoomMemberCount = `-- name: GetRoomMemberCount :one
SELECT COUNT(*) FROM room_members
WHERE room_id = $1
`

func (q *Queries) GetRoomMemberCount(ctx context.Context, roomID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getRoomMemberCount, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listJoinedRooms = `-- name: ListJoinedRooms :many
SELECT r.id, r.name, r.manager_id, r.capacity, rm.joined_at,
       (SELECT COUNT(*) FROM room_members WHERE room_id = r.id) AS member_count
FROM rooms r
JOIN room_members rm ON r.id = rm.room_id
WHERE rm.user_id = $1 AND r.deleted_at IS NULL
ORDER BY rm.joined_at DESC
`

type ListJoinedRoomsRow struct {
	ID          pgtype.UUID
	Name        string
	ManagerID   pgtype.UUID
	Capacity    int32
	JoinedAt    pgtype.Timestamptz
	MemberCount int64
}

func (q *Queries) ListJoinedRooms(ctx context.Context, userID pgtype.UUID) ([]ListJoinedRoomsRow, error) {
	rows, err := q.db.Query(ctx, listJoinedRooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJoinedRoomsRow
	for rows.Next() {
		var i ListJoinedRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ManagerID,
			&i.Capacity,
			&i.JoinedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMembers = `-- name: ListRoomMembers :many
SELECT u.id, u.username, rm.joined_at
FROM room_members rm
JOIN users u ON u.id = rm.user_id
JOIN rooms r ON r.id = rm.room_id
WHERE rm.room_id = $1 AND r.deleted_at IS NULL
ORDER BY rm.joined_at ASC
`

type ListRoomMembersRow struct {
	ID       pgtype.UUID
	Username string
	JoinedAt pgtype.Timestamptz
}

func (q *Queries) ListRoomMembers(ctx context.Context, roomID pgtype.UUID) ([]ListRoomMembersRow, error) {
	rows, err := q.db.Query(ctx, listRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomMembersRow
	for rows.Next() {
		var i ListRoomMembersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeDeletedRooms = `-- name: PurgeDeletedRooms :execrows
DELETE FROM rooms
WHERE deleted_at IS NOT NULL
  AND deleted_at < $1
`

func (q *Queries) PurgeDeletedRooms(ctx context.Context, deletedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeDeletedRooms, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchRooms = `-- name: SearchRooms :many
SELECT id, name, manager_id, capacity, created_at,
       COUNT(*) OVER() AS total_count,
       (SELECT COUNT(*) FROM room_members WHERE room_id = rooms.id) AS member_count
FROM rooms
WHERE name ILIKE '%' || $1 || '%' AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchRoomsParams struct {
	Column1 pgtype.Text
	Limit   int32
	Offset  int32
}

type SearchRoomsRow struct {
	ID          pgtype.UUID
	Name        string
	ManagerID   pgtype.UUID
	Capacity    int32
	CreatedAt   pgtype.Timestamptz
	TotalCount  int64
	MemberCount int64
}

func (q *Queries) SearchRooms(ctx context.Context, arg SearchRoomsParams) ([]SearchRoomsRow, error) {
	rows, err := q.db.Query(ctx, searchRooms, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRoomsRow
	for rows.Next() {
		var i SearchRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ManagerID,
			&i.Capacity,
			&i.CreatedAt,
			&i.TotalCount,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRoom = `-- name: SoftDeleteRoom :one
UPDATE rooms
SET deleted_at = $3
WHERE id = $1 AND manager_id = $2 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteRoomParams struct {
	ID        pgtype.UUID
	ManagerID pgtype.UUID
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SoftDeleteRoom(ctx context.Context, arg SoftDeleteRoomParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteRoom, arg.ID, arg.ManagerID, arg.DeletedAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET name = $2, capacity = $3
WHERE id = $1 AND manager_id = $4 AND deleted_at IS NULL
RETURNING id
`

type UpdateRoomParams struct {
	ID        pgtype.UUID
	Name      string
	Capacity  int32
	ManagerID pgtype.UUID
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.ID,
		arg.Name,
		arg.Capacity,
		arg.ManagerID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateRoomManager = `-- name: UpdateRoomManager :exec
UPDATE rooms
SET manager_id = $2
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateRoomManagerParams struct {
	ID        pgtype.UUID
	ManagerID pgtype.UUID
}

func (q *Queries) UpdateRoomManager(ctx context.Context, arg UpdateRoomManagerParams) error {
	_, err := q.db.Exec(ctx, updateRoomManager, arg.ID, arg.ManagerID)
	return err
}
