// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, username, password_hash, created_at
) VALUES (
  $1, $2, $3, $4
) RETURNING id, username, created_at
`

type CreateUserParams struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type CreateUserRow struct {
	ID        pgtype.UUID
	Username  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, created_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at, deleted_at FROM users
WHERE username = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, username, created_at FROM users
WHERE id = ANY($1::uuid[]) AND deleted_at IS NULL
`

type GetUsersByIDsRow struct {
	ID        pgtype.UUID
	Username  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetUsersByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByIDsRow
	for rows.Next() {
		var i GetUsersByIDsRow
		if err := rows.Scan(&i.ID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeDeletedUsers = `-- name: PurgeDeletedUsers :execrows
DELETE FROM users
WHERE deleted_at IS NOT NULL
  AND deleted_at < $1
`

func (q *Queries) PurgeDeletedUsers(ctx context.Context, deletedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeDeletedUsers, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users
SET deleted_at = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteUserParams struct {
	ID        pgtype.UUID
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, arg.ID, arg.DeletedAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
