rules:
  - seriesQuery: 'gochat_ws_connections_active{namespace!="",pod!=""}'
    resources:
      overrides:
        namespace:
          resource: namespace
        pod:
          resource: pod
    name:
      matches: '^gochat_ws_connections_active$'
      as: 'gochat_ws_connections_active'
    metricsQuery: 'sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)'
