// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	chat "go-chat-msa/internal/chat"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetHistory provides a mock function with given fields: ctx, roomID, limit, joinedAt
func (_m *MockRepository) GetHistory(ctx context.Context, roomID string, limit int64, joinedAt time.Time) ([]*chat.Message, error) {
	ret := _m.Called(ctx, roomID, limit, joinedAt)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 []*chat.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, time.Time) ([]*chat.Message, error)); ok {
		return rf(ctx, roomID, limit, joinedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, time.Time) []*chat.Message); ok {
		r0 = rf(ctx, roomID, limit, joinedAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*chat.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, time.Time) error); ok {
		r1 = rf(ctx, roomID, limit, joinedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistory'
type MockRepository_GetHistory_Call struct {
	*mock.Call
}

// GetHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - limit int64
//   - joinedAt time.Time
func (_e *MockRepository_Expecter) GetHistory(ctx interface{}, roomID interface{}, limit interface{}, joinedAt interface{}) *MockRepository_GetHistory_Call {
	return &MockRepository_GetHistory_Call{Call: _e.mock.On("GetHistory", ctx, roomID, limit, joinedAt)}
}

func (_c *MockRepository_GetHistory_Call) Run(run func(ctx context.Context, roomID string, limit int64, joinedAt time.Time)) *MockRepository_GetHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRepository_GetHistory_Call) Return(_a0 []*chat.Message, _a1 error) *MockRepository_GetHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetHistory_Call) RunAndReturn(run func(context.Context, string, int64, time.Time) ([]*chat.Message, error)) *MockRepository_GetHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastSequenceNumber provides a mock function with given fields: ctx, roomID
func (_m *MockRepository) GetLastSequenceNumber(ctx context.Context, roomID string) (int64, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetLastSequenceNumber")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, roomID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetLastSequenceNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastSequenceNumber'
type MockRepository_GetLastSequenceNumber_Call struct {
	*mock.Call
}

// GetLastSequenceNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *MockRepository_Expecter) GetLastSequenceNumber(ctx interface{}, roomID interface{}) *MockRepository_GetLastSequenceNumber_Call {
	return &MockRepository_GetLastSequenceNumber_Call{Call: _e.mock.On("GetLastSequenceNumber", ctx, roomID)}
}

func (_c *MockRepository_GetLastSequenceNumber_Call) Run(run func(ctx context.Context, roomID string)) *MockRepository_GetLastSequenceNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetLastSequenceNumber_Call) Return(_a0 int64, _a1 error) *MockRepository_GetLastSequenceNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetLastSequenceNumber_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockRepository_GetLastSequenceNumber_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMany provides a mock function with given fields: ctx, msgs
func (_m *MockRepository) SaveMany(ctx context.Context, msgs []*chat.Message) error {
	ret := _m.Called(ctx, msgs)

	if len(ret) == 0 {
		panic("no return value specified for SaveMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*chat.Message) error); ok {
		r0 = rf(ctx, msgs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SaveMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMany'
type MockRepository_SaveMany_Call struct {
	*mock.Call
}

// SaveMany is a helper method to define mock.On call
//   - ctx context.Context
//   - msgs []*chat.Message
func (_e *MockRepository_Expecter) SaveMany(ctx interface{}, msgs interface{}) *MockRepository_SaveMany_Call {
	return &MockRepository_SaveMany_Call{Call: _e.mock.On("SaveMany", ctx, msgs)}
}

func (_c *MockRepository_SaveMany_Call) Run(run func(ctx context.Context, msgs []*chat.Message)) *MockRepository_SaveMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*chat.Message))
	})
	return _c
}

func (_c *MockRepository_SaveMany_Call) Return(_a0 error) *MockRepository_SaveMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SaveMany_Call) RunAndReturn(run func(context.Context, []*chat.Message) error) *MockRepository_SaveMany_Call {
	_c.Call.Return(run)
	return _c
}

// SyncMessages provides a mock function with given fields: ctx, roomID, lastSeq, limit, joinedAt
func (_m *MockRepository) SyncMessages(ctx context.Context, roomID string, lastSeq int64, limit int64, joinedAt time.Time) ([]*chat.Message, error) {
	ret := _m.Called(ctx, roomID, lastSeq, limit, joinedAt)

	if len(ret) == 0 {
		panic("no return value specified for SyncMessages")
	}

	var r0 []*chat.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, time.Time) ([]*chat.Message, error)); ok {
		return rf(ctx, roomID, lastSeq, limit, joinedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, time.Time) []*chat.Message); ok {
		r0 = rf(ctx, roomID, lastSeq, limit, joinedAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*chat.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64, time.Time) error); ok {
		r1 = rf(ctx, roomID, lastSeq, limit, joinedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_SyncMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncMessages'
type MockRepository_SyncMessages_Call struct {
	*mock.Call
}

// SyncMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - lastSeq int64
//   - limit int64
//   - joinedAt time.Time
func (_e *MockRepository_Expecter) SyncMessages(ctx interface{}, roomID interface{}, lastSeq interface{}, limit interface{}, joinedAt interface{}) *MockRepository_SyncMessages_Call {
	return &MockRepository_SyncMessages_Call{Call: _e.mock.On("SyncMessages", ctx, roomID, lastSeq, limit, joinedAt)}
}

func (_c *MockRepository_SyncMessages_Call) Run(run func(ctx context.Context, roomID string, lastSeq int64, limit int64, joinedAt time.Time)) *MockRepository_SyncMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64), args[4].(time.Time))
	})
	return _c
}

func (_c *MockRepository_SyncMessages_Call) Return(_a0 []*chat.Message, _a1 error) *MockRepository_SyncMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_SyncMessages_Call) RunAndReturn(run func(context.Context, string, int64, int64, time.Time) ([]*chat.Message, error)) *MockRepository_SyncMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
