// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/chat/v1/chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ClientMsgId   string                 `protobuf:"bytes,5,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ListMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ListMessagesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ListMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMessagesRequest) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

type ListMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ListMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type SyncMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	JoinedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	AfterMessageId string                 `protobuf:"bytes,5,opt,name=after_message_id,json=afterMessageId,proto3" json:"after_message_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncMessagesRequest) Reset() {
	*x = SyncMessagesRequest{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessagesRequest) ProtoMessage() {}

func (x *SyncMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessagesRequest.ProtoReflect.Descriptor instead.
func (*SyncMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *SyncMessagesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SyncMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SyncMessagesRequest) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *SyncMessagesRequest) GetAfterMessageId() string {
	if x != nil {
		return x.AfterMessageId
	}
	return ""
}

type SyncMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMessagesResponse) Reset() {
	*x = SyncMessagesResponse{}
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessagesResponse) ProtoMessage() {}

func (x *SyncMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chat_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessagesResponse.ProtoReflect.Descriptor instead.
func (*SyncMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chat_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *SyncMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SyncMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_api_proto_chat_v1_chat_proto protoreflect.FileDescriptor

const file_api_proto_chat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/chat/v1/chat.proto\x12\achat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\"\n" +
	"\rclient_msg_id\x18\x05 \x01(\tR\vclientMsgId\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampJ\x04\b\a\x10\bR\x0fsequence_number\"}\n" +
	"\x13ListMessagesRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x127\n" +
	"\tjoined_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"_\n" +
	"\x14ListMessagesResponse\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.chat.v1.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\xc3\x01\n" +
	"\x13SyncMessagesRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x127\n" +
	"\tjoined_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x12(\n" +
	"\x10after_message_id\x18\x05 \x01(\tR\x0eafterMessageIdJ\x04\b\x02\x10\x03R\x14last_sequence_number\"_\n" +
	"\x14SyncMessagesResponse\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.chat.v1.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore2\xa7\x01\n" +
	"\vChatService\x12K\n" +
	"\fListMessages\x12\x1c.chat.v1.ListMessagesRequest\x1a\x1d.chat.v1.ListMessagesResponse\x12K\n" +
	"\fSyncMessages\x12\x1c.chat.v1.SyncMessagesRequest\x1a\x1d.chat.v1.SyncMessagesResponseB\x1fZ\x1dgo-chat-msa/api/proto/v1/chatb\x06proto3"

var (
	file_api_proto_chat_v1_chat_proto_rawDescOnce sync.Once
	file_api_proto_chat_v1_chat_proto_rawDescData []byte
)

func file_api_proto_chat_v1_chat_proto_rawDescGZIP() []byte {
	file_api_proto_chat_v1_chat_proto_rawDescOnce.Do(func() {
		file_api_proto_chat_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_chat_v1_chat_proto_rawDesc), len(file_api_proto_chat_v1_chat_proto_rawDesc)))
	})
	return file_api_proto_chat_v1_chat_proto_rawDescData
}

var file_api_proto_chat_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_chat_v1_chat_proto_goTypes = []any{
	(*Message)(nil),               // 0: chat.v1.Message
	(*ListMessagesRequest)(nil),   // 1: chat.v1.ListMessagesRequest
	(*ListMessagesResponse)(nil),  // 2: chat.v1.ListMessagesResponse
	(*SyncMessagesRequest)(nil),   // 3: chat.v1.SyncMessagesRequest
	(*SyncMessagesResponse)(nil),  // 4: chat.v1.SyncMessagesResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_api_proto_chat_v1_chat_proto_depIdxs = []int32{
	5, // 0: chat.v1.Message.timestamp:type_name -> google.protobuf.Timestamp
	5, // 1: chat.v1.ListMessagesRequest.joined_at:type_name -> google.protobuf.Timestamp
	0, // 2: chat.v1.ListMessagesResponse.messages:type_name -> chat.v1.Message
	5, // 3: chat.v1.SyncMessagesRequest.joined_at:type_name -> google.protobuf.Timestamp
	0, // 4: chat.v1.SyncMessagesResponse.messages:type_name -> chat.v1.Message
	1, // 5: chat.v1.ChatService.ListMessages:input_type -> chat.v1.ListMessagesRequest
	3, // 6: chat.v1.ChatService.SyncMessages:input_type -> chat.v1.SyncMessagesRequest
	2, // 7: chat.v1.ChatService.ListMessages:output_type -> chat.v1.ListMessagesResponse
	4, // 8: chat.v1.ChatService.SyncMessages:output_type -> chat.v1.SyncMessagesResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_chat_v1_chat_proto_init() }
func file_api_proto_chat_v1_chat_proto_init() {
	if File_api_proto_chat_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_chat_v1_chat_proto_rawDesc), len(file_api_proto_chat_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_chat_v1_chat_proto_goTypes,
		DependencyIndexes: file_api_proto_chat_v1_chat_proto_depIdxs,
		MessageInfos:      file_api_proto_chat_v1_chat_proto_msgTypes,
	}.Build()
	File_api_proto_chat_v1_chat_proto = out.File
	file_api_proto_chat_v1_chat_proto_goTypes = nil
	file_api_proto_chat_v1_chat_proto_depIdxs = nil
}
