// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-chat-msa/api/proto/chat/v1"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockChatServiceClient creates a new instance of MockChatServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatServiceClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockChatServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockChatServiceClient is an autogenerated mock type for the ChatServiceClient type
type MockChatServiceClient struct {
	mock.Mock
}

type MockChatServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatServiceClient) EXPECT() *MockChatServiceClient_Expecter {
	return &MockChatServiceClient_Expecter{mock: &_m.Mock}
}

// ListMessages provides a mock function for the type MockChatServiceClient
func (_mock *MockChatServiceClient) ListMessages(ctx context.Context, in *chat.ListMessagesRequest, opts ...grpc.CallOption) (*chat.ListMessagesResponse, error) {
	// grpc.CallOption
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListMessages")
	}

	var r0 *chat.ListMessagesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *chat.ListMessagesRequest, ...grpc.CallOption) (*chat.ListMessagesResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *chat.ListMessagesRequest, ...grpc.CallOption) *chat.ListMessagesResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.ListMessagesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *chat.ListMessagesRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatServiceClient_ListMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMessages'
type MockChatServiceClient_ListMessages_Call struct {
	*mock.Call
}

// ListMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - in *chat.ListMessagesRequest
//   - opts ...grpc.CallOption
func (_e *MockChatServiceClient_Expecter) ListMessages(ctx any, in any, opts ...any) *MockChatServiceClient_ListMessages_Call {
	return &MockChatServiceClient_ListMessages_Call{Call: _e.mock.On("ListMessages",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *MockChatServiceClient_ListMessages_Call) Run(run func(ctx context.Context, in *chat.ListMessagesRequest, opts ...grpc.CallOption)) *MockChatServiceClient_ListMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *chat.ListMessagesRequest
		if args[1] != nil {
			arg1 = args[1].(*chat.ListMessagesRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatServiceClient_ListMessages_Call) Return(listMessagesResponse *chat.ListMessagesResponse, err error) *MockChatServiceClient_ListMessages_Call {
	_c.Call.Return(listMessagesResponse, err)
	return _c
}

func (_c *MockChatServiceClient_ListMessages_Call) RunAndReturn(run func(ctx context.Context, in *chat.ListMessagesRequest, opts ...grpc.CallOption) (*chat.ListMessagesResponse, error)) *MockChatServiceClient_ListMessages_Call {
	_c.Call.Return(run)
	return _c
}

// SyncMessages provides a mock function for the type MockChatServiceClient
func (_mock *MockChatServiceClient) SyncMessages(ctx context.Context, in *chat.SyncMessagesRequest, opts ...grpc.CallOption) (*chat.SyncMessagesResponse, error) {
	// grpc.CallOption
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SyncMessages")
	}

	var r0 *chat.SyncMessagesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *chat.SyncMessagesRequest, ...grpc.CallOption) (*chat.SyncMessagesResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *chat.SyncMessagesRequest, ...grpc.CallOption) *chat.SyncMessagesResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.SyncMessagesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *chat.SyncMessagesRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatServiceClient_SyncMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncMessages'
type MockChatServiceClient_SyncMessages_Call struct {
	*mock.Call
}

// SyncMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - in *chat.SyncMessagesRequest
//   - opts ...grpc.CallOption
func (_e *MockChatServiceClient_Expecter) SyncMessages(ctx any, in any, opts ...any) *MockChatServiceClient_SyncMessages_Call {
	return &MockChatServiceClient_SyncMessages_Call{Call: _e.mock.On("SyncMessages",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *MockChatServiceClient_SyncMessages_Call) Run(run func(ctx context.Context, in *chat.SyncMessagesRequest, opts ...grpc.CallOption)) *MockChatServiceClient_SyncMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *chat.SyncMessagesRequest
		if args[1] != nil {
			arg1 = args[1].(*chat.SyncMessagesRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatServiceClient_SyncMessages_Call) Return(syncMessagesResponse *chat.SyncMessagesResponse, err error) *MockChatServiceClient_SyncMessages_Call {
	_c.Call.Return(syncMessagesResponse, err)
	return _c
}

func (_c *MockChatServiceClient_SyncMessages_Call) RunAndReturn(run func(ctx context.Context, in *chat.SyncMessagesRequest, opts ...grpc.CallOption) (*chat.SyncMessagesResponse, error)) *MockChatServiceClient_SyncMessages_Call {
	_c.Call.Return(run)
	return _c
}
