// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	user "go-chat-msa/api/proto/user/v1"
)

// MockUserServiceClient is an autogenerated mock type for the UserServiceClient type
type MockUserServiceClient struct {
	mock.Mock
}

type MockUserServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserServiceClient) EXPECT() *MockUserServiceClient_Expecter {
	return &MockUserServiceClient_Expecter{mock: &_m.Mock}
}

// CreateRoom provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) CreateRoom(ctx context.Context, in *user.CreateRoomRequest, opts ...grpc.CallOption) (*user.CreateRoomResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 *user.CreateRoomResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.CreateRoomRequest, ...grpc.CallOption) (*user.CreateRoomResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.CreateRoomRequest, ...grpc.CallOption) *user.CreateRoomResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.CreateRoomResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.CreateRoomRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_CreateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoom'
type MockUserServiceClient_CreateRoom_Call struct {
	*mock.Call
}

// CreateRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - in *user.CreateRoomRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) CreateRoom(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_CreateRoom_Call {
	return &MockUserServiceClient_CreateRoom_Call{Call: _e.mock.On("CreateRoom",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_CreateRoom_Call) Run(run func(ctx context.Context, in *user.CreateRoomRequest, opts ...grpc.CallOption)) *MockUserServiceClient_CreateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*user.CreateRoomRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_CreateRoom_Call) Return(_a0 *user.CreateRoomResponse, _a1 error) *MockUserServiceClient_CreateRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_CreateRoom_Call) RunAndReturn(run func(context.Context, *user.CreateRoomRequest, ...grpc.CallOption) (*user.CreateRoomResponse, error)) *MockUserServiceClient_CreateRoom_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) CreateUser(ctx context.Context, in *user.CreateUserRequest, opts ...grpc.CallOption) (*user.CreateUserResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *user.CreateUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.CreateUserRequest, ...grpc.CallOption) (*user.CreateUserResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.CreateUserRequest, ...grpc.CallOption) *user.CreateUserResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.CreateUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.CreateUserRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserServiceClient_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - in *user.CreateUserRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) CreateUser(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_CreateUser_Call {
	return &MockUserServiceClient_CreateUser_Call{Call: _e.mock.On("CreateUser",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_CreateUser_Call) Run(run func(ctx context.Context, in *user.CreateUserRequest, opts ...grpc.CallOption)) *MockUserServiceClient_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*user.CreateUserRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_CreateUser_Call) Return(_a0 *user.CreateUserResponse, _a1 error) *MockUserServiceClient_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_CreateUser_Call) RunAndReturn(run func(context.Context, *user.CreateUserRequest, ...grpc.CallOption) (*user.CreateUserResponse, error)) *MockUserServiceClient_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRoom provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) DeleteRoom(ctx context.Context, in *user.DeleteRoomRequest, opts ...grpc.CallOption) (*user.DeleteRoomResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoom")
	}

	var r0 *user.DeleteRoomResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.DeleteRoomRequest, ...grpc.CallOption) (*user.DeleteRoomResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.DeleteRoomRequest, ...grpc.CallOption) *user.DeleteRoomResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.DeleteRoomResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.DeleteRoomRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_DeleteRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRoom'
type MockUserServiceClient_DeleteRoom_Call struct {
	*mock.Call
}

// DeleteRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - in *user.DeleteRoomRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) DeleteRoom(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_DeleteRoom_Call {
	return &MockUserServiceClient_DeleteRoom_Call{Call: _e.mock.On("DeleteRoom",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_DeleteRoom_Call) Run(run func(ctx context.Context, in *user.DeleteRoomRequest, opts ...grpc.CallOption)) *MockUserServiceClient_DeleteRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*user.DeleteRoomRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_DeleteRoom_Call) Return(_a0 *user.DeleteRoomResponse, _a1 error) *MockUserServiceClient_DeleteRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_DeleteRoom_Call) RunAndReturn(run func(context.Context, *user.DeleteRoomRequest, ...grpc.CallOption) (*user.DeleteRoomResponse, error)) *MockUserServiceClient_DeleteRoom_Call {
	_c.Call.Return(run)
	return _c
}

// GetMemberJoinedAt provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) GetMemberJoinedAt(ctx context.Context, in *user.GetMemberJoinedAtRequest, opts ...grpc.CallOption) (*user.GetMemberJoinedAtResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberJoinedAt")
	}

	var r0 *user.GetMemberJoinedAtResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.GetMemberJoinedAtRequest, ...grpc.CallOption) (*user.GetMemberJoinedAtResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.GetMemberJoinedAtRequest, ...grpc.CallOption) *user.GetMemberJoinedAtResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.GetMemberJoinedAtResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.GetMemberJoinedAtRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_GetMemberJoinedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberJoinedAt'
type MockUserServiceClient_GetMemberJoinedAt_Call struct {
	*mock.Call
}

// GetMemberJoinedAt is a helper method to define mock.On call
//   - ctx context.Context
//   - in *user.GetMemberJoinedAtRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) GetMemberJoinedAt(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_GetMemberJoinedAt_Call {
	return &MockUserServiceClient_GetMemberJoinedAt_Call{Call: _e.mock.On("GetMemberJoinedAt",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_GetMemberJoinedAt_Call) Run(run func(ctx context.Context, in *user.GetMemberJoinedAtRequest, opts ...grpc.CallOption)) *MockUserServiceClient_GetMemberJoinedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*user.GetMemberJoinedAtRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_GetMemberJoinedAt_Call) Return(_a0 *user.GetMemberJoinedAtResponse, _a1 error) *MockUserServiceClient_GetMemberJoinedAt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_GetMemberJoinedAt_Call) RunAndReturn(run func(context.Context, *user.GetMemberJoinedAtRequest, ...grpc.CallOption) (*user.GetMemberJoinedAtResponse, error)) *MockUserServiceClient_GetMemberJoinedAt_Call {
	_c.Call.Return(run)
	return _c
}

// JoinRoom provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) JoinRoom(ctx context.Context, in *user.JoinRoomRequest, opts ...grpc.CallOption) (*user.JoinRoomResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for JoinRoom")
	}

	var r0 *user.JoinRoomResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.JoinRoomRequest, ...grpc.CallOption) (*user.JoinRoomResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.JoinRoomRequest, ...grpc.CallOption) *user.JoinRoomResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.JoinRoomResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.JoinRoomRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_JoinRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinRoom'
type MockUserServiceClient_JoinRoom_Call struct {
	*mock.Call
}

// JoinRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - in *user.JoinRoomRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) JoinRoom(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_JoinRoom_Call {
	return &MockUserServiceClient_JoinRoom_Call{Call: _e.mock.On("JoinRoom",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_JoinRoom_Call) Run(run func(ctx context.Context, in *user.JoinRoomRequest, opts ...grpc.CallOption)) *MockUserServiceClient_JoinRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*user.JoinRoomRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_JoinRoom_Call) Return(_a0 *user.JoinRoomResponse, _a1 error) *MockUserServiceClient_JoinRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_JoinRoom_Call) RunAndReturn(run func(context.Context, *user.JoinRoomRequest, ...grpc.CallOption) (*user.JoinRoomResponse, error)) *MockUserServiceClient_JoinRoom_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveRoom provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) LeaveRoom(ctx context.Context, in *user.LeaveRoomRequest, opts ...grpc.CallOption) (*user.LeaveRoomResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LeaveRoom")
	}

	var r0 *user.LeaveRoomResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.LeaveRoomRequest, ...grpc.CallOption) (*user.LeaveRoomResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.LeaveRoomRequest, ...grpc.CallOption) *user.LeaveRoomResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.LeaveRoomResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.LeaveRoomRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_LeaveRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveRoom'
type MockUserServiceClient_LeaveRoom_Call struct {
	*mock.Call
}

// LeaveRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - in *user.LeaveRoomRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) LeaveRoom(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_LeaveRoom_Call {
	return &MockUserServiceClient_LeaveRoom_Call{Call: _e.mock.On("LeaveRoom",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_LeaveRoom_Call) Run(run func(ctx context.Context, in *user.LeaveRoomRequest, opts ...grpc.CallOption)) *MockUserServiceClient_LeaveRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*user.LeaveRoomRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_LeaveRoom_Call) Return(_a0 *user.LeaveRoomResponse, _a1 error) *MockUserServiceClient_LeaveRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_LeaveRoom_Call) RunAndReturn(run func(context.Context, *user.LeaveRoomRequest, ...grpc.CallOption) (*user.LeaveRoomResponse, error)) *MockUserServiceClient_LeaveRoom_Call {
	_c.Call.Return(run)
	return _c
}

// ListJoinedRooms provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) ListJoinedRooms(ctx context.Context, in *user.ListJoinedRoomsRequest, opts ...grpc.CallOption) (*user.ListJoinedRoomsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListJoinedRooms")
	}

	var r0 *user.ListJoinedRoomsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.ListJoinedRoomsRequest, ...grpc.CallOption) (*user.ListJoinedRoomsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.ListJoinedRoomsRequest, ...grpc.CallOption) *user.ListJoinedRoomsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.ListJoinedRoomsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.ListJoinedRoomsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_ListJoinedRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListJoinedRooms'
type MockUserServiceClient_ListJoinedRooms_Call struct {
	*mock.Call
}

// ListJoinedRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - in *user.ListJoinedRoomsRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) ListJoinedRooms(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_ListJoinedRooms_Call {
	return &MockUserServiceClient_ListJoinedRooms_Call{Call: _e.mock.On("ListJoinedRooms",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_ListJoinedRooms_Call) Run(run func(ctx context.Context, in *user.ListJoinedRoomsRequest, opts ...grpc.CallOption)) *MockUserServiceClient_ListJoinedRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*user.ListJoinedRoomsRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_ListJoinedRooms_Call) Return(_a0 *user.ListJoinedRoomsResponse, _a1 error) *MockUserServiceClient_ListJoinedRooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_ListJoinedRooms_Call) RunAndReturn(run func(context.Context, *user.ListJoinedRoomsRequest, ...grpc.CallOption) (*user.ListJoinedRoomsResponse, error)) *MockUserServiceClient_ListJoinedRooms_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoomMembers provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) ListRoomMembers(ctx context.Context, in *user.ListRoomMembersRequest, opts ...grpc.CallOption) (*user.ListRoomMembersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListRoomMembers")
	}

	var r0 *user.ListRoomMembersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.ListRoomMembersRequest, ...grpc.CallOption) (*user.ListRoomMembersResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.ListRoomMembersRequest, ...grpc.CallOption) *user.ListRoomMembersResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.ListRoomMembersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.ListRoomMembersRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_ListRoomMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoomMembers'
type MockUserServiceClient_ListRoomMembers_Call struct {
	*mock.Call
}

// ListRoomMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - in *user.ListRoomMembersRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) ListRoomMembers(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_ListRoomMembers_Call {
	return &MockUserServiceClient_ListRoomMembers_Call{Call: _e.mock.On("ListRoomMembers",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_ListRoomMembers_Call) Run(run func(ctx context.Context, in *user.ListRoomMembersRequest, opts ...grpc.CallOption)) *MockUserServiceClient_ListRoomMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*user.ListRoomMembersRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_ListRoomMembers_Call) Return(_a0 *user.ListRoomMembersResponse, _a1 error) *MockUserServiceClient_ListRoomMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_ListRoomMembers_Call) RunAndReturn(run func(context.Context, *user.ListRoomMembersRequest, ...grpc.CallOption) (*user.ListRoomMembersResponse, error)) *MockUserServiceClient_ListRoomMembers_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) RefreshToken(ctx context.Context, in *user.RefreshTokenRequest, opts ...grpc.CallOption) (*user.RefreshTokenResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *user.RefreshTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.RefreshTokenRequest, ...grpc.CallOption) (*user.RefreshTokenResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.RefreshTokenRequest, ...grpc.CallOption) *user.RefreshTokenResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.RefreshTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.RefreshTokenRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockUserServiceClient_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - in *user.RefreshTokenRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) RefreshToken(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_RefreshToken_Call {
	return &MockUserServiceClient_RefreshToken_Call{Call: _e.mock.On("RefreshToken",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_RefreshToken_Call) Run(run func(ctx context.Context, in *user.RefreshTokenRequest, opts ...grpc.CallOption)) *MockUserServiceClient_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*user.RefreshTokenRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_RefreshToken_Call) Return(_a0 *user.RefreshTokenResponse, _a1 error) *MockUserServiceClient_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_RefreshToken_Call) RunAndReturn(run func(context.Context, *user.RefreshTokenRequest, ...grpc.CallOption) (*user.RefreshTokenResponse, error)) *MockUserServiceClient_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) RevokeToken(ctx context.Context, in *user.RevokeTokenRequest, opts ...grpc.CallOption) (*user.RevokeTokenResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 *user.RevokeTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.RevokeTokenRequest, ...grpc.CallOption) (*user.RevokeTokenResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.RevokeTokenRequest, ...grpc.CallOption) *user.RevokeTokenResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.RevokeTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.RevokeTokenRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockUserServiceClient_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - in *user.RevokeTokenRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) RevokeToken(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_RevokeToken_Call {
	return &MockUserServiceClient_RevokeToken_Call{Call: _e.mock.On("RevokeToken",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_RevokeToken_Call) Run(run func(ctx context.Context, in *user.RevokeTokenRequest, opts ...grpc.CallOption)) *MockUserServiceClient_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*user.RevokeTokenRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_RevokeToken_Call) Return(_a0 *user.RevokeTokenResponse, _a1 error) *MockUserServiceClient_RevokeToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_RevokeToken_Call) RunAndReturn(run func(context.Context, *user.RevokeTokenRequest, ...grpc.CallOption) (*user.RevokeTokenResponse, error)) *MockUserServiceClient_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}

// SearchRooms provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) SearchRooms(ctx context.Context, in *user.SearchRoomsRequest, opts ...grpc.CallOption) (*user.SearchRoomsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SearchRooms")
	}

	var r0 *user.SearchRoomsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.SearchRoomsRequest, ...grpc.CallOption) (*user.SearchRoomsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.SearchRoomsRequest, ...grpc.CallOption) *user.SearchRoomsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.SearchRoomsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.SearchRoomsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_SearchRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchRooms'
type MockUserServiceClient_SearchRooms_Call struct {
	*mock.Call
}

// SearchRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - in *user.SearchRoomsRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) SearchRooms(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_SearchRooms_Call {
	return &MockUserServiceClient_SearchRooms_Call{Call: _e.mock.On("SearchRooms",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_SearchRooms_Call) Run(run func(ctx context.Context, in *user.SearchRoomsRequest, opts ...grpc.CallOption)) *MockUserServiceClient_SearchRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*user.SearchRoomsRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_SearchRooms_Call) Return(_a0 *user.SearchRoomsResponse, _a1 error) *MockUserServiceClient_SearchRooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_SearchRooms_Call) RunAndReturn(run func(context.Context, *user.SearchRoomsRequest, ...grpc.CallOption) (*user.SearchRoomsResponse, error)) *MockUserServiceClient_SearchRooms_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRoom provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) UpdateRoom(ctx context.Context, in *user.UpdateRoomRequest, opts ...grpc.CallOption) (*user.UpdateRoomResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoom")
	}

	var r0 *user.UpdateRoomResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.UpdateRoomRequest, ...grpc.CallOption) (*user.UpdateRoomResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.UpdateRoomRequest, ...grpc.CallOption) *user.UpdateRoomResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UpdateRoomResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.UpdateRoomRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_UpdateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRoom'
type MockUserServiceClient_UpdateRoom_Call struct {
	*mock.Call
}

// UpdateRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - in *user.UpdateRoomRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) UpdateRoom(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_UpdateRoom_Call {
	return &MockUserServiceClient_UpdateRoom_Call{Call: _e.mock.On("UpdateRoom",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_UpdateRoom_Call) Run(run func(ctx context.Context, in *user.UpdateRoomRequest, opts ...grpc.CallOption)) *MockUserServiceClient_UpdateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*user.UpdateRoomRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_UpdateRoom_Call) Return(_a0 *user.UpdateRoomResponse, _a1 error) *MockUserServiceClient_UpdateRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_UpdateRoom_Call) RunAndReturn(run func(context.Context, *user.UpdateRoomRequest, ...grpc.CallOption) (*user.UpdateRoomResponse, error)) *MockUserServiceClient_UpdateRoom_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyRoomMember provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) VerifyRoomMember(ctx context.Context, in *user.VerifyRoomMemberRequest, opts ...grpc.CallOption) (*user.VerifyRoomMemberResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for VerifyRoomMember")
	}

	var r0 *user.VerifyRoomMemberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.VerifyRoomMemberRequest, ...grpc.CallOption) (*user.VerifyRoomMemberResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.VerifyRoomMemberRequest, ...grpc.CallOption) *user.VerifyRoomMemberResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.VerifyRoomMemberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.VerifyRoomMemberRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_VerifyRoomMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyRoomMember'
type MockUserServiceClient_VerifyRoomMember_Call struct {
	*mock.Call
}

// VerifyRoomMember is a helper method to define mock.On call
//   - ctx context.Context
//   - in *user.VerifyRoomMemberRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) VerifyRoomMember(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_VerifyRoomMember_Call {
	return &MockUserServiceClient_VerifyRoomMember_Call{Call: _e.mock.On("VerifyRoomMember",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_VerifyRoomMember_Call) Run(run func(ctx context.Context, in *user.VerifyRoomMemberRequest, opts ...grpc.CallOption)) *MockUserServiceClient_VerifyRoomMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*user.VerifyRoomMemberRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_VerifyRoomMember_Call) Return(_a0 *user.VerifyRoomMemberResponse, _a1 error) *MockUserServiceClient_VerifyRoomMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_VerifyRoomMember_Call) RunAndReturn(run func(context.Context, *user.VerifyRoomMemberRequest, ...grpc.CallOption) (*user.VerifyRoomMemberResponse, error)) *MockUserServiceClient_VerifyRoomMember_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyUser provides a mock function with given fields: ctx, in, opts
func (_m *MockUserServiceClient) VerifyUser(ctx context.Context, in *user.VerifyUserRequest, opts ...grpc.CallOption) (*user.VerifyUserResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for VerifyUser")
	}

	var r0 *user.VerifyUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.VerifyUserRequest, ...grpc.CallOption) (*user.VerifyUserResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.VerifyUserRequest, ...grpc.CallOption) *user.VerifyUserResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.VerifyUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.VerifyUserRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceClient_VerifyUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyUser'
type MockUserServiceClient_VerifyUser_Call struct {
	*mock.Call
}

// VerifyUser is a helper method to define mock.On call
//   - ctx context.Context
//   - in *user.VerifyUserRequest
//   - opts ...grpc.CallOption
func (_e *MockUserServiceClient_Expecter) VerifyUser(ctx interface{}, in interface{}, opts ...interface{}) *MockUserServiceClient_VerifyUser_Call {
	return &MockUserServiceClient_VerifyUser_Call{Call: _e.mock.On("VerifyUser",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserServiceClient_VerifyUser_Call) Run(run func(ctx context.Context, in *user.VerifyUserRequest, opts ...grpc.CallOption)) *MockUserServiceClient_VerifyUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*user.VerifyUserRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserServiceClient_VerifyUser_Call) Return(_a0 *user.VerifyUserResponse, _a1 error) *MockUserServiceClient_VerifyUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceClient_VerifyUser_Call) RunAndReturn(run func(context.Context, *user.VerifyUserRequest, ...grpc.CallOption) (*user.VerifyUserResponse, error)) *MockUserServiceClient_VerifyUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserServiceClient creates a new instance of MockUserServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserServiceClient {
	mock := &MockUserServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
