// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	chat "go-chat-msa/api/proto/chat/v1"

	emptypb "google.golang.org/protobuf/types/known/emptypb"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MockChatServiceClient is an autogenerated mock type for the ChatServiceClient type
type MockChatServiceClient struct {
	mock.Mock
}

type MockChatServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatServiceClient) EXPECT() *MockChatServiceClient_Expecter {
	return &MockChatServiceClient_Expecter{mock: &_m.Mock}
}

// BatchCreateMessages provides a mock function with given fields: ctx, in, opts
func (_m *MockChatServiceClient) BatchCreateMessages(ctx context.Context, in *chat.BatchCreateMessagesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for BatchCreateMessages")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *chat.BatchCreateMessagesRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *chat.BatchCreateMessagesRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *chat.BatchCreateMessagesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatServiceClient_BatchCreateMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchCreateMessages'
type MockChatServiceClient_BatchCreateMessages_Call struct {
	*mock.Call
}

// BatchCreateMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - in *chat.BatchCreateMessagesRequest
//   - opts ...grpc.CallOption
func (_e *MockChatServiceClient_Expecter) BatchCreateMessages(ctx interface{}, in interface{}, opts ...interface{}) *MockChatServiceClient_BatchCreateMessages_Call {
	return &MockChatServiceClient_BatchCreateMessages_Call{Call: _e.mock.On("BatchCreateMessages",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockChatServiceClient_BatchCreateMessages_Call) Run(run func(ctx context.Context, in *chat.BatchCreateMessagesRequest, opts ...grpc.CallOption)) *MockChatServiceClient_BatchCreateMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*chat.BatchCreateMessagesRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockChatServiceClient_BatchCreateMessages_Call) Return(_a0 *emptypb.Empty, _a1 error) *MockChatServiceClient_BatchCreateMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatServiceClient_BatchCreateMessages_Call) RunAndReturn(run func(context.Context, *chat.BatchCreateMessagesRequest, ...grpc.CallOption) (*emptypb.Empty, error)) *MockChatServiceClient_BatchCreateMessages_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastSequenceNumber provides a mock function with given fields: ctx, in, opts
func (_m *MockChatServiceClient) GetLastSequenceNumber(ctx context.Context, in *chat.GetLastSequenceNumberRequest, opts ...grpc.CallOption) (*chat.GetLastSequenceNumberResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetLastSequenceNumber")
	}

	var r0 *chat.GetLastSequenceNumberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *chat.GetLastSequenceNumberRequest, ...grpc.CallOption) (*chat.GetLastSequenceNumberResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *chat.GetLastSequenceNumberRequest, ...grpc.CallOption) *chat.GetLastSequenceNumberResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.GetLastSequenceNumberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *chat.GetLastSequenceNumberRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatServiceClient_GetLastSequenceNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastSequenceNumber'
type MockChatServiceClient_GetLastSequenceNumber_Call struct {
	*mock.Call
}

// GetLastSequenceNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - in *chat.GetLastSequenceNumberRequest
//   - opts ...grpc.CallOption
func (_e *MockChatServiceClient_Expecter) GetLastSequenceNumber(ctx interface{}, in interface{}, opts ...interface{}) *MockChatServiceClient_GetLastSequenceNumber_Call {
	return &MockChatServiceClient_GetLastSequenceNumber_Call{Call: _e.mock.On("GetLastSequenceNumber",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockChatServiceClient_GetLastSequenceNumber_Call) Run(run func(ctx context.Context, in *chat.GetLastSequenceNumberRequest, opts ...grpc.CallOption)) *MockChatServiceClient_GetLastSequenceNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*chat.GetLastSequenceNumberRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockChatServiceClient_GetLastSequenceNumber_Call) Return(_a0 *chat.GetLastSequenceNumberResponse, _a1 error) *MockChatServiceClient_GetLastSequenceNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatServiceClient_GetLastSequenceNumber_Call) RunAndReturn(run func(context.Context, *chat.GetLastSequenceNumberRequest, ...grpc.CallOption) (*chat.GetLastSequenceNumberResponse, error)) *MockChatServiceClient_GetLastSequenceNumber_Call {
	_c.Call.Return(run)
	return _c
}

// ListMessages provides a mock function with given fields: ctx, in, opts
func (_m *MockChatServiceClient) ListMessages(ctx context.Context, in *chat.ListMessagesRequest, opts ...grpc.CallOption) (*chat.ListMessagesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListMessages")
	}

	var r0 *chat.ListMessagesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *chat.ListMessagesRequest, ...grpc.CallOption) (*chat.ListMessagesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *chat.ListMessagesRequest, ...grpc.CallOption) *chat.ListMessagesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.ListMessagesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *chat.ListMessagesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatServiceClient_ListMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMessages'
type MockChatServiceClient_ListMessages_Call struct {
	*mock.Call
}

// ListMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - in *chat.ListMessagesRequest
//   - opts ...grpc.CallOption
func (_e *MockChatServiceClient_Expecter) ListMessages(ctx interface{}, in interface{}, opts ...interface{}) *MockChatServiceClient_ListMessages_Call {
	return &MockChatServiceClient_ListMessages_Call{Call: _e.mock.On("ListMessages",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockChatServiceClient_ListMessages_Call) Run(run func(ctx context.Context, in *chat.ListMessagesRequest, opts ...grpc.CallOption)) *MockChatServiceClient_ListMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*chat.ListMessagesRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockChatServiceClient_ListMessages_Call) Return(_a0 *chat.ListMessagesResponse, _a1 error) *MockChatServiceClient_ListMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatServiceClient_ListMessages_Call) RunAndReturn(run func(context.Context, *chat.ListMessagesRequest, ...grpc.CallOption) (*chat.ListMessagesResponse, error)) *MockChatServiceClient_ListMessages_Call {
	_c.Call.Return(run)
	return _c
}

// SyncMessages provides a mock function with given fields: ctx, in, opts
func (_m *MockChatServiceClient) SyncMessages(ctx context.Context, in *chat.SyncMessagesRequest, opts ...grpc.CallOption) (*chat.SyncMessagesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SyncMessages")
	}

	var r0 *chat.SyncMessagesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *chat.SyncMessagesRequest, ...grpc.CallOption) (*chat.SyncMessagesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *chat.SyncMessagesRequest, ...grpc.CallOption) *chat.SyncMessagesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.SyncMessagesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *chat.SyncMessagesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatServiceClient_SyncMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncMessages'
type MockChatServiceClient_SyncMessages_Call struct {
	*mock.Call
}

// SyncMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - in *chat.SyncMessagesRequest
//   - opts ...grpc.CallOption
func (_e *MockChatServiceClient_Expecter) SyncMessages(ctx interface{}, in interface{}, opts ...interface{}) *MockChatServiceClient_SyncMessages_Call {
	return &MockChatServiceClient_SyncMessages_Call{Call: _e.mock.On("SyncMessages",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockChatServiceClient_SyncMessages_Call) Run(run func(ctx context.Context, in *chat.SyncMessagesRequest, opts ...grpc.CallOption)) *MockChatServiceClient_SyncMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*chat.SyncMessagesRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockChatServiceClient_SyncMessages_Call) Return(_a0 *chat.SyncMessagesResponse, _a1 error) *MockChatServiceClient_SyncMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatServiceClient_SyncMessages_Call) RunAndReturn(run func(context.Context, *chat.SyncMessagesRequest, ...grpc.CallOption) (*chat.SyncMessagesResponse, error)) *MockChatServiceClient_SyncMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatServiceClient creates a new instance of MockChatServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatServiceClient {
	mock := &MockChatServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
