// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	db "go-chat-msa/internal/user/db"

	mock "github.com/stretchr/testify/mock"

	pgtype "github.com/jackc/pgx/v5/pgtype"
)

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// CreateRefreshToken provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateRefreshToken(ctx context.Context, arg db.CreateRefreshTokenParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateRefreshTokenParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_CreateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefreshToken'
type MockQuerier_CreateRefreshToken_Call struct {
	*mock.Call
}

// CreateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateRefreshTokenParams
func (_e *MockQuerier_Expecter) CreateRefreshToken(ctx interface{}, arg interface{}) *MockQuerier_CreateRefreshToken_Call {
	return &MockQuerier_CreateRefreshToken_Call{Call: _e.mock.On("CreateRefreshToken", ctx, arg)}
}

func (_c *MockQuerier_CreateRefreshToken_Call) Run(run func(ctx context.Context, arg db.CreateRefreshTokenParams)) *MockQuerier_CreateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateRefreshTokenParams))
	})
	return _c
}

func (_c *MockQuerier_CreateRefreshToken_Call) Return(_a0 error) *MockQuerier_CreateRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_CreateRefreshToken_Call) RunAndReturn(run func(context.Context, db.CreateRefreshTokenParams) error) *MockQuerier_CreateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRoom provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateRoom(ctx context.Context, arg db.CreateRoomParams) (db.CreateRoomRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 db.CreateRoomRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateRoomParams) (db.CreateRoomRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateRoomParams) db.CreateRoomRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.CreateRoomRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateRoomParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoom'
type MockQuerier_CreateRoom_Call struct {
	*mock.Call
}

// CreateRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateRoomParams
func (_e *MockQuerier_Expecter) CreateRoom(ctx interface{}, arg interface{}) *MockQuerier_CreateRoom_Call {
	return &MockQuerier_CreateRoom_Call{Call: _e.mock.On("CreateRoom", ctx, arg)}
}

func (_c *MockQuerier_CreateRoom_Call) Run(run func(ctx context.Context, arg db.CreateRoomParams)) *MockQuerier_CreateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateRoomParams))
	})
	return _c
}

func (_c *MockQuerier_CreateRoom_Call) Return(_a0 db.CreateRoomRow, _a1 error) *MockQuerier_CreateRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateRoom_Call) RunAndReturn(run func(context.Context, db.CreateRoomParams) (db.CreateRoomRow, error)) *MockQuerier_CreateRoom_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRoomMember provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateRoomMember(ctx context.Context, arg db.CreateRoomMemberParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoomMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateRoomMemberParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_CreateRoomMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoomMember'
type MockQuerier_CreateRoomMember_Call struct {
	*mock.Call
}

// CreateRoomMember is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateRoomMemberParams
func (_e *MockQuerier_Expecter) CreateRoomMember(ctx interface{}, arg interface{}) *MockQuerier_CreateRoomMember_Call {
	return &MockQuerier_CreateRoomMember_Call{Call: _e.mock.On("CreateRoomMember", ctx, arg)}
}

func (_c *MockQuerier_CreateRoomMember_Call) Run(run func(ctx context.Context, arg db.CreateRoomMemberParams)) *MockQuerier_CreateRoomMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateRoomMemberParams))
	})
	return _c
}

func (_c *MockQuerier_CreateRoomMember_Call) Return(_a0 error) *MockQuerier_CreateRoomMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_CreateRoomMember_Call) RunAndReturn(run func(context.Context, db.CreateRoomMemberParams) error) *MockQuerier_CreateRoomMember_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.CreateUserRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 db.CreateUserRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) (db.CreateUserRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) db.CreateUserRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.CreateUserRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockQuerier_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateUserParams
func (_e *MockQuerier_Expecter) CreateUser(ctx interface{}, arg interface{}) *MockQuerier_CreateUser_Call {
	return &MockQuerier_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *MockQuerier_CreateUser_Call) Run(run func(ctx context.Context, arg db.CreateUserParams)) *MockQuerier_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateUserParams))
	})
	return _c
}

func (_c *MockQuerier_CreateUser_Call) Return(_a0 db.CreateUserRow, _a1 error) *MockQuerier_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateUser_Call) RunAndReturn(run func(context.Context, db.CreateUserParams) (db.CreateUserRow, error)) *MockQuerier_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredRefreshTokens provides a mock function with given fields: ctx
func (_m *MockQuerier) DeleteExpiredRefreshTokens(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredRefreshTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteExpiredRefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredRefreshTokens'
type MockQuerier_DeleteExpiredRefreshTokens_Call struct {
	*mock.Call
}

// DeleteExpiredRefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) DeleteExpiredRefreshTokens(ctx interface{}) *MockQuerier_DeleteExpiredRefreshTokens_Call {
	return &MockQuerier_DeleteExpiredRefreshTokens_Call{Call: _e.mock.On("DeleteExpiredRefreshTokens", ctx)}
}

func (_c *MockQuerier_DeleteExpiredRefreshTokens_Call) Run(run func(ctx context.Context)) *MockQuerier_DeleteExpiredRefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQuerier_DeleteExpiredRefreshTokens_Call) Return(_a0 error) *MockQuerier_DeleteExpiredRefreshTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteExpiredRefreshTokens_Call) RunAndReturn(run func(context.Context) error) *MockQuerier_DeleteExpiredRefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRefreshTokenByHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockQuerier) DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshTokenByHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteRefreshTokenByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshTokenByHash'
type MockQuerier_DeleteRefreshTokenByHash_Call struct {
	*mock.Call
}

// DeleteRefreshTokenByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockQuerier_Expecter) DeleteRefreshTokenByHash(ctx interface{}, tokenHash interface{}) *MockQuerier_DeleteRefreshTokenByHash_Call {
	return &MockQuerier_DeleteRefreshTokenByHash_Call{Call: _e.mock.On("DeleteRefreshTokenByHash", ctx, tokenHash)}
}

func (_c *MockQuerier_DeleteRefreshTokenByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockQuerier_DeleteRefreshTokenByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerier_DeleteRefreshTokenByHash_Call) Return(_a0 error) *MockQuerier_DeleteRefreshTokenByHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteRefreshTokenByHash_Call) RunAndReturn(run func(context.Context, string) error) *MockQuerier_DeleteRefreshTokenByHash_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRefreshTokensByUserID provides a mock function with given fields: ctx, userID
func (_m *MockQuerier) DeleteRefreshTokensByUserID(ctx context.Context, userID pgtype.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshTokensByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteRefreshTokensByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshTokensByUserID'
type MockQuerier_DeleteRefreshTokensByUserID_Call struct {
	*mock.Call
}

// DeleteRefreshTokensByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID pgtype.UUID
func (_e *MockQuerier_Expecter) DeleteRefreshTokensByUserID(ctx interface{}, userID interface{}) *MockQuerier_DeleteRefreshTokensByUserID_Call {
	return &MockQuerier_DeleteRefreshTokensByUserID_Call{Call: _e.mock.On("DeleteRefreshTokensByUserID", ctx, userID)}
}

func (_c *MockQuerier_DeleteRefreshTokensByUserID_Call) Run(run func(ctx context.Context, userID pgtype.UUID)) *MockQuerier_DeleteRefreshTokensByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgtype.UUID))
	})
	return _c
}

func (_c *MockQuerier_DeleteRefreshTokensByUserID_Call) Return(_a0 error) *MockQuerier_DeleteRefreshTokensByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteRefreshTokensByUserID_Call) RunAndReturn(run func(context.Context, pgtype.UUID) error) *MockQuerier_DeleteRefreshTokensByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRoomMember provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) DeleteRoomMember(ctx context.Context, arg db.DeleteRoomMemberParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoomMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.DeleteRoomMemberParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteRoomMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRoomMember'
type MockQuerier_DeleteRoomMember_Call struct {
	*mock.Call
}

// DeleteRoomMember is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.DeleteRoomMemberParams
func (_e *MockQuerier_Expecter) DeleteRoomMember(ctx interface{}, arg interface{}) *MockQuerier_DeleteRoomMember_Call {
	return &MockQuerier_DeleteRoomMember_Call{Call: _e.mock.On("DeleteRoomMember", ctx, arg)}
}

func (_c *MockQuerier_DeleteRoomMember_Call) Run(run func(ctx context.Context, arg db.DeleteRoomMemberParams)) *MockQuerier_DeleteRoomMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.DeleteRoomMemberParams))
	})
	return _c
}

func (_c *MockQuerier_DeleteRoomMember_Call) Return(_a0 error) *MockQuerier_DeleteRoomMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteRoomMember_Call) RunAndReturn(run func(context.Context, db.DeleteRoomMemberParams) error) *MockQuerier_DeleteRoomMember_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsRoomMember provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) ExistsRoomMember(ctx context.Context, arg db.ExistsRoomMemberParams) (bool, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ExistsRoomMember")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ExistsRoomMemberParams) (bool, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ExistsRoomMemberParams) bool); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ExistsRoomMemberParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_ExistsRoomMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsRoomMember'
type MockQuerier_ExistsRoomMember_Call struct {
	*mock.Call
}

// ExistsRoomMember is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ExistsRoomMemberParams
func (_e *MockQuerier_Expecter) ExistsRoomMember(ctx interface{}, arg interface{}) *MockQuerier_ExistsRoomMember_Call {
	return &MockQuerier_ExistsRoomMember_Call{Call: _e.mock.On("ExistsRoomMember", ctx, arg)}
}

func (_c *MockQuerier_ExistsRoomMember_Call) Run(run func(ctx context.Context, arg db.ExistsRoomMemberParams)) *MockQuerier_ExistsRoomMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ExistsRoomMemberParams))
	})
	return _c
}

func (_c *MockQuerier_ExistsRoomMember_Call) Return(_a0 bool, _a1 error) *MockQuerier_ExistsRoomMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_ExistsRoomMember_Call) RunAndReturn(run func(context.Context, db.ExistsRoomMemberParams) (bool, error)) *MockQuerier_ExistsRoomMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetMemberJoinedAt provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) GetMemberJoinedAt(ctx context.Context, arg db.GetMemberJoinedAtParams) (pgtype.Timestamptz, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberJoinedAt")
	}

	var r0 pgtype.Timestamptz
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetMemberJoinedAtParams) (pgtype.Timestamptz, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetMemberJoinedAtParams) pgtype.Timestamptz); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(pgtype.Timestamptz)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetMemberJoinedAtParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetMemberJoinedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberJoinedAt'
type MockQuerier_GetMemberJoinedAt_Call struct {
	*mock.Call
}

// GetMemberJoinedAt is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.GetMemberJoinedAtParams
func (_e *MockQuerier_Expecter) GetMemberJoinedAt(ctx interface{}, arg interface{}) *MockQuerier_GetMemberJoinedAt_Call {
	return &MockQuerier_GetMemberJoinedAt_Call{Call: _e.mock.On("GetMemberJoinedAt", ctx, arg)}
}

func (_c *MockQuerier_GetMemberJoinedAt_Call) Run(run func(ctx context.Context, arg db.GetMemberJoinedAtParams)) *MockQuerier_GetMemberJoinedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.GetMemberJoinedAtParams))
	})
	return _c
}

func (_c *MockQuerier_GetMemberJoinedAt_Call) Return(_a0 pgtype.Timestamptz, _a1 error) *MockQuerier_GetMemberJoinedAt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetMemberJoinedAt_Call) RunAndReturn(run func(context.Context, db.GetMemberJoinedAtParams) (pgtype.Timestamptz, error)) *MockQuerier_GetMemberJoinedAt_Call {
	_c.Call.Return(run)
	return _c
}

// GetOldestRoomMember provides a mock function with given fields: ctx, roomID
func (_m *MockQuerier) GetOldestRoomMember(ctx context.Context, roomID pgtype.UUID) (pgtype.UUID, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetOldestRoomMember")
	}

	var r0 pgtype.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (pgtype.UUID, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) pgtype.UUID); ok {
		r0 = rf(ctx, roomID)
	} else {
		r0 = ret.Get(0).(pgtype.UUID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetOldestRoomMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOldestRoomMember'
type MockQuerier_GetOldestRoomMember_Call struct {
	*mock.Call
}

// GetOldestRoomMember is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID pgtype.UUID
func (_e *MockQuerier_Expecter) GetOldestRoomMember(ctx interface{}, roomID interface{}) *MockQuerier_GetOldestRoomMember_Call {
	return &MockQuerier_GetOldestRoomMember_Call{Call: _e.mock.On("GetOldestRoomMember", ctx, roomID)}
}

func (_c *MockQuerier_GetOldestRoomMember_Call) Run(run func(ctx context.Context, roomID pgtype.UUID)) *MockQuerier_GetOldestRoomMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgtype.UUID))
	})
	return _c
}

func (_c *MockQuerier_GetOldestRoomMember_Call) Return(_a0 pgtype.UUID, _a1 error) *MockQuerier_GetOldestRoomMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetOldestRoomMember_Call) RunAndReturn(run func(context.Context, pgtype.UUID) (pgtype.UUID, error)) *MockQuerier_GetOldestRoomMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshTokenByHashForUpdate provides a mock function with given fields: ctx, tokenHash
func (_m *MockQuerier) GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash string) (db.RefreshToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokenByHashForUpdate")
	}

	var r0 db.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.RefreshToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.RefreshToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(db.RefreshToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetRefreshTokenByHashForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshTokenByHashForUpdate'
type MockQuerier_GetRefreshTokenByHashForUpdate_Call struct {
	*mock.Call
}

// GetRefreshTokenByHashForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockQuerier_Expecter) GetRefreshTokenByHashForUpdate(ctx interface{}, tokenHash interface{}) *MockQuerier_GetRefreshTokenByHashForUpdate_Call {
	return &MockQuerier_GetRefreshTokenByHashForUpdate_Call{Call: _e.mock.On("GetRefreshTokenByHashForUpdate", ctx, tokenHash)}
}

func (_c *MockQuerier_GetRefreshTokenByHashForUpdate_Call) Run(run func(ctx context.Context, tokenHash string)) *MockQuerier_GetRefreshTokenByHashForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerier_GetRefreshTokenByHashForUpdate_Call) Return(_a0 db.RefreshToken, _a1 error) *MockQuerier_GetRefreshTokenByHashForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetRefreshTokenByHashForUpdate_Call) RunAndReturn(run func(context.Context, string) (db.RefreshToken, error)) *MockQuerier_GetRefreshTokenByHashForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoomForUpdate provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetRoomForUpdate(ctx context.Context, id pgtype.UUID) (db.GetRoomForUpdateRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomForUpdate")
	}

	var r0 db.GetRoomForUpdateRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (db.GetRoomForUpdateRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) db.GetRoomForUpdateRow); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.GetRoomForUpdateRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetRoomForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoomForUpdate'
type MockQuerier_GetRoomForUpdate_Call struct {
	*mock.Call
}

// GetRoomForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockQuerier_Expecter) GetRoomForUpdate(ctx interface{}, id interface{}) *MockQuerier_GetRoomForUpdate_Call {
	return &MockQuerier_GetRoomForUpdate_Call{Call: _e.mock.On("GetRoomForUpdate", ctx, id)}
}

func (_c *MockQuerier_GetRoomForUpdate_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockQuerier_GetRoomForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgtype.UUID))
	})
	return _c
}

func (_c *MockQuerier_GetRoomForUpdate_Call) Return(_a0 db.GetRoomForUpdateRow, _a1 error) *MockQuerier_GetRoomForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetRoomForUpdate_Call) RunAndReturn(run func(context.Context, pgtype.UUID) (db.GetRoomForUpdateRow, error)) *MockQuerier_GetRoomForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoomMemberCount provides a mock function with given fields: ctx, roomID
func (_m *MockQuerier) GetRoomMemberCount(ctx context.Context, roomID pgtype.UUID) (int64, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomMemberCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (int64, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) int64); ok {
		r0 = rf(ctx, roomID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetRoomMemberCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoomMemberCount'
type MockQuerier_GetRoomMemberCount_Call struct {
	*mock.Call
}

// GetRoomMemberCount is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID pgtype.UUID
func (_e *MockQuerier_Expecter) GetRoomMemberCount(ctx interface{}, roomID interface{}) *MockQuerier_GetRoomMemberCount_Call {
	return &MockQuerier_GetRoomMemberCount_Call{Call: _e.mock.On("GetRoomMemberCount", ctx, roomID)}
}

func (_c *MockQuerier_GetRoomMemberCount_Call) Run(run func(ctx context.Context, roomID pgtype.UUID)) *MockQuerier_GetRoomMemberCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgtype.UUID))
	})
	return _c
}

func (_c *MockQuerier_GetRoomMemberCount_Call) Return(_a0 int64, _a1 error) *MockQuerier_GetRoomMemberCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetRoomMemberCount_Call) RunAndReturn(run func(context.Context, pgtype.UUID) (int64, error)) *MockQuerier_GetRoomMemberCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetUserByID(ctx context.Context, id pgtype.UUID) (db.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (db.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) db.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockQuerier_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockQuerier_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockQuerier_GetUserByID_Call {
	return &MockQuerier_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockQuerier_GetUserByID_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockQuerier_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgtype.UUID))
	})
	return _c
}

func (_c *MockQuerier_GetUserByID_Call) Return(_a0 db.User, _a1 error) *MockQuerier_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetUserByID_Call) RunAndReturn(run func(context.Context, pgtype.UUID) (db.User, error)) *MockQuerier_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function with given fields: ctx, username
func (_m *MockQuerier) GetUserByUsername(ctx context.Context, username string) (db.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockQuerier_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockQuerier_Expecter) GetUserByUsername(ctx interface{}, username interface{}) *MockQuerier_GetUserByUsername_Call {
	return &MockQuerier_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *MockQuerier_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockQuerier_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerier_GetUserByUsername_Call) Return(_a0 db.User, _a1 error) *MockQuerier_GetUserByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetUserByUsername_Call) RunAndReturn(run func(context.Context, string) (db.User, error)) *MockQuerier_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// ListJoinedRooms provides a mock function with given fields: ctx, userID
func (_m *MockQuerier) ListJoinedRooms(ctx context.Context, userID pgtype.UUID) ([]db.ListJoinedRoomsRow, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListJoinedRooms")
	}

	var r0 []db.ListJoinedRoomsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]db.ListJoinedRoomsRow, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []db.ListJoinedRoomsRow); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ListJoinedRoomsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_ListJoinedRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListJoinedRooms'
type MockQuerier_ListJoinedRooms_Call struct {
	*mock.Call
}

// ListJoinedRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - userID pgtype.UUID
func (_e *MockQuerier_Expecter) ListJoinedRooms(ctx interface{}, userID interface{}) *MockQuerier_ListJoinedRooms_Call {
	return &MockQuerier_ListJoinedRooms_Call{Call: _e.mock.On("ListJoinedRooms", ctx, userID)}
}

func (_c *MockQuerier_ListJoinedRooms_Call) Run(run func(ctx context.Context, userID pgtype.UUID)) *MockQuerier_ListJoinedRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgtype.UUID))
	})
	return _c
}

func (_c *MockQuerier_ListJoinedRooms_Call) Return(_a0 []db.ListJoinedRoomsRow, _a1 error) *MockQuerier_ListJoinedRooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_ListJoinedRooms_Call) RunAndReturn(run func(context.Context, pgtype.UUID) ([]db.ListJoinedRoomsRow, error)) *MockQuerier_ListJoinedRooms_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoomMembers provides a mock function with given fields: ctx, roomID
func (_m *MockQuerier) ListRoomMembers(ctx context.Context, roomID pgtype.UUID) ([]db.ListRoomMembersRow, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for ListRoomMembers")
	}

	var r0 []db.ListRoomMembersRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]db.ListRoomMembersRow, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []db.ListRoomMembersRow); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ListRoomMembersRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_ListRoomMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoomMembers'
type MockQuerier_ListRoomMembers_Call struct {
	*mock.Call
}

// ListRoomMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID pgtype.UUID
func (_e *MockQuerier_Expecter) ListRoomMembers(ctx interface{}, roomID interface{}) *MockQuerier_ListRoomMembers_Call {
	return &MockQuerier_ListRoomMembers_Call{Call: _e.mock.On("ListRoomMembers", ctx, roomID)}
}

func (_c *MockQuerier_ListRoomMembers_Call) Run(run func(ctx context.Context, roomID pgtype.UUID)) *MockQuerier_ListRoomMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgtype.UUID))
	})
	return _c
}

func (_c *MockQuerier_ListRoomMembers_Call) Return(_a0 []db.ListRoomMembersRow, _a1 error) *MockQuerier_ListRoomMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_ListRoomMembers_Call) RunAndReturn(run func(context.Context, pgtype.UUID) ([]db.ListRoomMembersRow, error)) *MockQuerier_ListRoomMembers_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRefreshTokenUsed provides a mock function with given fields: ctx, id
func (_m *MockQuerier) MarkRefreshTokenUsed(ctx context.Context, id pgtype.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkRefreshTokenUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_MarkRefreshTokenUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRefreshTokenUsed'
type MockQuerier_MarkRefreshTokenUsed_Call struct {
	*mock.Call
}

// MarkRefreshTokenUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockQuerier_Expecter) MarkRefreshTokenUsed(ctx interface{}, id interface{}) *MockQuerier_MarkRefreshTokenUsed_Call {
	return &MockQuerier_MarkRefreshTokenUsed_Call{Call: _e.mock.On("MarkRefreshTokenUsed", ctx, id)}
}

func (_c *MockQuerier_MarkRefreshTokenUsed_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockQuerier_MarkRefreshTokenUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgtype.UUID))
	})
	return _c
}

func (_c *MockQuerier_MarkRefreshTokenUsed_Call) Return(_a0 error) *MockQuerier_MarkRefreshTokenUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_MarkRefreshTokenUsed_Call) RunAndReturn(run func(context.Context, pgtype.UUID) error) *MockQuerier_MarkRefreshTokenUsed_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeDeletedRooms provides a mock function with given fields: ctx, deletedAt
func (_m *MockQuerier) PurgeDeletedRooms(ctx context.Context, deletedAt pgtype.Timestamptz) (int64, error) {
	ret := _m.Called(ctx, deletedAt)

	if len(ret) == 0 {
		panic("no return value specified for PurgeDeletedRooms")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.Timestamptz) (int64, error)); ok {
		return rf(ctx, deletedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.Timestamptz) int64); ok {
		r0 = rf(ctx, deletedAt)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.Timestamptz) error); ok {
		r1 = rf(ctx, deletedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_PurgeDeletedRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeDeletedRooms'
type MockQuerier_PurgeDeletedRooms_Call struct {
	*mock.Call
}

// PurgeDeletedRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - deletedAt pgtype.Timestamptz
func (_e *MockQuerier_Expecter) PurgeDeletedRooms(ctx interface{}, deletedAt interface{}) *MockQuerier_PurgeDeletedRooms_Call {
	return &MockQuerier_PurgeDeletedRooms_Call{Call: _e.mock.On("PurgeDeletedRooms", ctx, deletedAt)}
}

func (_c *MockQuerier_PurgeDeletedRooms_Call) Run(run func(ctx context.Context, deletedAt pgtype.Timestamptz)) *MockQuerier_PurgeDeletedRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgtype.Timestamptz))
	})
	return _c
}

func (_c *MockQuerier_PurgeDeletedRooms_Call) Return(_a0 int64, _a1 error) *MockQuerier_PurgeDeletedRooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_PurgeDeletedRooms_Call) RunAndReturn(run func(context.Context, pgtype.Timestamptz) (int64, error)) *MockQuerier_PurgeDeletedRooms_Call {
	_c.Call.Return(run)
	return _c
}

// SearchRooms provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) SearchRooms(ctx context.Context, arg db.SearchRoomsParams) ([]db.SearchRoomsRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SearchRooms")
	}

	var r0 []db.SearchRoomsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.SearchRoomsParams) ([]db.SearchRoomsRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.SearchRoomsParams) []db.SearchRoomsRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.SearchRoomsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.SearchRoomsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_SearchRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchRooms'
type MockQuerier_SearchRooms_Call struct {
	*mock.Call
}

// SearchRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.SearchRoomsParams
func (_e *MockQuerier_Expecter) SearchRooms(ctx interface{}, arg interface{}) *MockQuerier_SearchRooms_Call {
	return &MockQuerier_SearchRooms_Call{Call: _e.mock.On("SearchRooms", ctx, arg)}
}

func (_c *MockQuerier_SearchRooms_Call) Run(run func(ctx context.Context, arg db.SearchRoomsParams)) *MockQuerier_SearchRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.SearchRoomsParams))
	})
	return _c
}

func (_c *MockQuerier_SearchRooms_Call) Return(_a0 []db.SearchRoomsRow, _a1 error) *MockQuerier_SearchRooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_SearchRooms_Call) RunAndReturn(run func(context.Context, db.SearchRoomsParams) ([]db.SearchRoomsRow, error)) *MockQuerier_SearchRooms_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteRoom provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) SoftDeleteRoom(ctx context.Context, arg db.SoftDeleteRoomParams) (pgtype.UUID, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteRoom")
	}

	var r0 pgtype.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.SoftDeleteRoomParams) (pgtype.UUID, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.SoftDeleteRoomParams) pgtype.UUID); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(pgtype.UUID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.SoftDeleteRoomParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_SoftDeleteRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteRoom'
type MockQuerier_SoftDeleteRoom_Call struct {
	*mock.Call
}

// SoftDeleteRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.SoftDeleteRoomParams
func (_e *MockQuerier_Expecter) SoftDeleteRoom(ctx interface{}, arg interface{}) *MockQuerier_SoftDeleteRoom_Call {
	return &MockQuerier_SoftDeleteRoom_Call{Call: _e.mock.On("SoftDeleteRoom", ctx, arg)}
}

func (_c *MockQuerier_SoftDeleteRoom_Call) Run(run func(ctx context.Context, arg db.SoftDeleteRoomParams)) *MockQuerier_SoftDeleteRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.SoftDeleteRoomParams))
	})
	return _c
}

func (_c *MockQuerier_SoftDeleteRoom_Call) Return(_a0 pgtype.UUID, _a1 error) *MockQuerier_SoftDeleteRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_SoftDeleteRoom_Call) RunAndReturn(run func(context.Context, db.SoftDeleteRoomParams) (pgtype.UUID, error)) *MockQuerier_SoftDeleteRoom_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRoom provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateRoom(ctx context.Context, arg db.UpdateRoomParams) (pgtype.UUID, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoom")
	}

	var r0 pgtype.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateRoomParams) (pgtype.UUID, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateRoomParams) pgtype.UUID); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(pgtype.UUID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateRoomParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_UpdateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRoom'
type MockQuerier_UpdateRoom_Call struct {
	*mock.Call
}

// UpdateRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateRoomParams
func (_e *MockQuerier_Expecter) UpdateRoom(ctx interface{}, arg interface{}) *MockQuerier_UpdateRoom_Call {
	return &MockQuerier_UpdateRoom_Call{Call: _e.mock.On("UpdateRoom", ctx, arg)}
}

func (_c *MockQuerier_UpdateRoom_Call) Run(run func(ctx context.Context, arg db.UpdateRoomParams)) *MockQuerier_UpdateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateRoomParams))
	})
	return _c
}

func (_c *MockQuerier_UpdateRoom_Call) Return(_a0 pgtype.UUID, _a1 error) *MockQuerier_UpdateRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_UpdateRoom_Call) RunAndReturn(run func(context.Context, db.UpdateRoomParams) (pgtype.UUID, error)) *MockQuerier_UpdateRoom_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRoomManager provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateRoomManager(ctx context.Context, arg db.UpdateRoomManagerParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoomManager")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateRoomManagerParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_UpdateRoomManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRoomManager'
type MockQuerier_UpdateRoomManager_Call struct {
	*mock.Call
}

// UpdateRoomManager is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateRoomManagerParams
func (_e *MockQuerier_Expecter) UpdateRoomManager(ctx interface{}, arg interface{}) *MockQuerier_UpdateRoomManager_Call {
	return &MockQuerier_UpdateRoomManager_Call{Call: _e.mock.On("UpdateRoomManager", ctx, arg)}
}

func (_c *MockQuerier_UpdateRoomManager_Call) Run(run func(ctx context.Context, arg db.UpdateRoomManagerParams)) *MockQuerier_UpdateRoomManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateRoomManagerParams))
	})
	return _c
}

func (_c *MockQuerier_UpdateRoomManager_Call) Return(_a0 error) *MockQuerier_UpdateRoomManager_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_UpdateRoomManager_Call) RunAndReturn(run func(context.Context, db.UpdateRoomManagerParams) error) *MockQuerier_UpdateRoomManager_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
