apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  labels:
    app.kubernetes.io/name: websocket-service
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: go-chat-msa
    app.kubernetes.io/instance: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    targetPort: http
  selector:
    app.kubernetes.io/name: websocket-service
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: go-chat-msa
    app.kubernetes.io/instance: {{ .Release.Namespace }}
