apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: go-chat-msa
    app.kubernetes.io/instance: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: go-chat-msa
    app.kubernetes.io/instance: {{ .Release.Namespace }}
