ENV: "dev"

TELEMETRY:
  OTEL_ENDPOINT: "alloy:4318"
  PYROSCOPE_ENDPOINT: "http://pyroscope:4040"

REGISTRY:
  USER_SERVICE:
    HOST: "user-service"
  CHAT_SERVICE:
    HOST: "chat-service"
  WS_GATEWAY:
    HOST: "ws-gateway"
  WEBSOCKET_ENDPOINTS: ["websocket-service-1:8081", "websocket-service-2:8081"]

JWT:
  SECRET: "dev_secret_key_1234"

INTERNAL:
  SECRET: "dev_internal_secret_1234"

DB:
  POSTGRES_URL: "postgres://postgres@postgres:5432/go_chat?sslmode=disable"
  MONGO_URI: "mongodb://mongo:27017"

API_GATEWAY:
  CORS:
    ALLOWED_ORIGINS: ["*"]

WS_GATEWAY:
  CORS:
    ALLOWED_ORIGINS: ["*"]
