apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-migrations
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: go-chat-msa
    app.kubernetes.io/instance: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "files/mongo-migrations/*").AsConfig | indent 2 }}
