apiVersion: v1
kind: ConfigMap
metadata:
  name: gochat-app-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: go-chat-msa
    app.kubernetes.io/instance: {{ .Release.Namespace }}
data:
  base.yaml: |
{{ .Values.global.appConfig.base | toYaml | indent 4 }}
  override.yaml: |
{{ .Values.global.appConfig.override | toYaml | indent 4 }}
