apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-chat

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patches/mongo-glibc-tunables.yaml

images:
  - name: go-chat-msa/api-gateway
    newTag: dev
  - name: go-chat-msa/ws-gateway
    newTag: dev
  - name: go-chat-msa/websocket-service
    newTag: dev
  - name: go-chat-msa/user-service
    newTag: dev
  - name: go-chat-msa/chat-service
    newTag: dev
  - name: go-chat-msa/frontend
    newTag: dev
  - name: go-chat-msa/retention-job
    newTag: dev
  - name: go-chat-msa/user-token-purge-job
    newTag: dev
