apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-chat-dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patches/grafana-root-url.yaml
  - path: patches/ingress-host.yaml
    target:
      kind: Ingress
      name: api-gateway
  - path: patches/ingress-host.yaml
    target:
      kind: Ingress
      name: ws-gateway-api
  - path: patches/ingress-host.yaml
    target:
      kind: Ingress
      name: ws-gateway-websocket
  - path: patches/ingress-host.yaml
    target:
      kind: Ingress
      name: swagger-ui
  - path: patches/ingress-host.yaml
    target:
      kind: Ingress
      name: grafana
  - path: patches/ingress-host.yaml
    target:
      kind: Ingress
      name: frontend

images:
  - name: go-chat-msa/api-gateway
    newTag: dev
  - name: go-chat-msa/ws-gateway
    newTag: dev
  - name: go-chat-msa/websocket-service
    newTag: dev
  - name: go-chat-msa/user-service
    newTag: dev
  - name: go-chat-msa/chat-service
    newTag: dev
  - name: go-chat-msa/frontend
    newTag: dev

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/part-of: go-chat-msa
      app.kubernetes.io/instance: go-chat-dev
