apiVersion: v1
kind: Namespace
metadata:
  name: go-chat-dev
  labels:
    app.kubernetes.io/name: go-chat-dev
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: go-chat-msa
    app.kubernetes.io/instance: go-chat-dev
